spring:
    config:
        import: optional:file:.env[.properties]
    datasource:
        url: jdbc:postgresql://localhost:35001/insurance-dev
        username: insurance-dev
        password: CLI-825.2025X
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true